version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5-node
    working_directory: ~/circle-ci
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "requirements.txt" }}
  test:
    docker:
      - image: circleci/python:3.7.5-node
    working_directory: ~/circle-ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Run unit test
          command: |
            . venv/bin/activate
            pytest
  static_analysis:
    docker:
      - image: circleci/python:3.7.5-node
    working_directory: ~/circle-ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: code style and quality check
          command: |
            . venv/bin/activate
            flake8 ./ --exclude=venv --output-file flake8-reports.txt
      - store_artifacts:
          path: flake8-reports.txt
          destination: flake8-reports.txt
      - run:
          # We want to generate code security report using bandit but we do not want it to fail the pipeline
          name: code security test
          command: |
            . venv/bin/activate
            bandit -r ./  --exclude venv -f txt -o code-security-report.txt || echo ""
      - store_artifacts:
          path: code-security-report.txt
          destination: code-security-report.txt
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - static_analysis:
          requires:
            - build